/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 -T bug 2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bug 2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box002.geometry} material={nodes.Box002.material} />
      <mesh geometry={nodes.Gem.geometry} material={materials.Ring_Crystal} />
      <mesh geometry={nodes.Line001.geometry} material={nodes.Line001.material} />
      <mesh geometry={nodes.Line049.geometry} material={nodes.Line049.material} />
    </group>
  )
}

useGLTF.preload('/bug 2-transformed.glb')
