/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 dore.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dore.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shape1.geometry} material={materials['Material #27']} position={[-10.005, -3.696, -0.035]} rotation={[Math.PI / 2, 0, 0]} scale={32.392} />
    </group>
  )
}

useGLTF.preload('/dore.glb')
